# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"b\n\x12RequestVoteRequest\x12\x13\n\x0b\x63\x61ndidateId\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x05\"8\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x08\")\n\x08LogEntry\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\x05\"\x93\x01\n\x14\x41ppendEntriesRequest\x12\x10\n\x08leaderId\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x05\x12\x14\n\x0cleaderCommit\x18\x05 \x01(\x05\x12\x1a\n\x07\x65ntries\x18\x06 \x03(\x0b\x32\t.LogEntry\"C\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0b\n\x03\x61\x63k\x18\x03 \x01(\x05\"%\n\x12ServeClientRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\"F\n\x13ServeClientResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x10\n\x08leaderId\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x32\xc0\x01\n\x04Raft\x12:\n\x0bRequestVote\x12\x13.RequestVoteRequest\x1a\x14.RequestVoteResponse\"\x00\x12@\n\rAppendEntries\x12\x15.AppendEntriesRequest\x1a\x16.AppendEntriesResponse\"\x00\x12:\n\x0bServeClient\x12\x13.ServeClientRequest\x1a\x14.ServeClientResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTVOTEREQUEST']._serialized_start=14
  _globals['_REQUESTVOTEREQUEST']._serialized_end=112
  _globals['_REQUESTVOTERESPONSE']._serialized_start=114
  _globals['_REQUESTVOTERESPONSE']._serialized_end=170
  _globals['_LOGENTRY']._serialized_start=172
  _globals['_LOGENTRY']._serialized_end=213
  _globals['_APPENDENTRIESREQUEST']._serialized_start=216
  _globals['_APPENDENTRIESREQUEST']._serialized_end=363
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=365
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=432
  _globals['_SERVECLIENTREQUEST']._serialized_start=434
  _globals['_SERVECLIENTREQUEST']._serialized_end=471
  _globals['_SERVECLIENTRESPONSE']._serialized_start=473
  _globals['_SERVECLIENTRESPONSE']._serialized_end=543
  _globals['_RAFT']._serialized_start=546
  _globals['_RAFT']._serialized_end=738
# @@protoc_insertion_point(module_scope)
